name: Detect Secrets

on:  
  pull_request:  
    branches: [main]  
  push:  
    branches: [main]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Unngå kloning av submoduler

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Bruk versjonen du har installert

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline
      
      - name: New secrets found
        run: |
          detect-secrets scan --baseline .secrets.baseline > new_scan.json
          if ! diff -q .secrets.baseline new_scan.json; then
            echo "New secrets found. Update basline if necesarry!"
            exit 1
          fi