name: Detect Secrets

on: [push, pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Unngå kloning av submoduler

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Bruk versjonen du har installert

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline