name: Security Requirements Report

on:
  schedule:
    - cron: '0 0 1 * *'  # Kjøres månedlig
  push:
    branches:
      - main
      - annSophie-po.1.1  # For testing
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
        # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

        # Step 2: Install the latest version of trivy
      - name: Installing trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.60.0_Linux-64bit.tar.gz
          tar -xzf trivy_0.60.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

        # Step 3: Scan the entire project for vulnerabilitiues using trivy
      - name: Scan repository for vulnerabilities (entire project)
        id: trivy
        run: |
          trivy fs --security-checks vuln,config --format json --output trivy-report.json --severity HIGH,CRITICAL --vuln-type os,library --ignore-unfixed .
