name: ps.3.1 

on:
  release:
    types: [published]

jobs: 
  archive: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug: Check current files
      - name: "Debug: List workspace files before packaging"
        run: ls -lah

      # Create a compressed archive of the source code
      - name: Package release
        run: tar -czvf release.tar.gz src/

      # Debug: Check if the tarball was created
      - name: Verify tarball creation
        run: |
          if [ ! -f release.tar.gz ]; then
            echo "Error: release.tar.gz was not created!"
            exit 1
          fi
          echo "release.tar.gz exists."
          ls -lah release.tar.gz

      # Generate SHA256 checksum
      - name: Calculate SHA256 checksum
        run: sha256sum release.tar.gz > release.sha256

      # Verify checksum file
      - name: Verify checksum file
        run: |
          if [ ! -f release.sha256 ]; then
            echo "Error: release.sha256 was not created!"
            exit 1
          fi
          echo "release.sha256 exists."
          cat release.sha256
