name: ps.3.1-test2

on:
  release:
    types: [published]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create backup of repository
      run: | 
        git clone --mirror https://github.com/advisense/iac-azure-terraform-example.git 
        sudo apt-get install zip 
        zip iac-azure-terraform-example.zip -r iac-azure-terraform-example.git 

    - name: Generate sha checksum 
      run: sha256sum iac-azure-terraform-example.zip > iac-azure-terraform-example.zip.sha256sum

    - name: Upload backup and checksum as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backup-zip
        path: iac-azure-terraform-example.zip

    - name: Upload checksum as artifact
      uses: actions/upload-artifact@v3
      with:
        name: backup-sha256
        path: iac-azure-terraform-example.zip.sha256sum

    - name: Create GitHub Issue with backup and checksum links
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        ISSUE_TITLE="Backup of repository and checksum for ${{ github.event.release.tag_name }} on $(date)"
        ISSUE_BODY=$(cat <<EOF

        ## Backup of repository and checksum for ${{ github.event.release.tag_name }} on $(date)
        ### Backup file
        Download backup-zip
        ### Checksum file
        Download backup-sha256
        ### Details
        - Repository: ${{ github.repository }}
        - Release: ${{ github.event.release.tag_name }}
        - Date: $(date)

        EOF
                )
                gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "backup"

