name: Backup Repository

on:
  release:
    types: [published]

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create backup archive
      run: |
        tar -czf backup-${{ github.ref_name }}.tar.gz .

    - name: Upload backup to remote server
      env:
        REMOTE_SERVER: ${{ secrets.REMOTE_SERVER }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        scp backup-${{ github.ref_name }}.tar.gz $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PATH

    - name: Verify integrity
      run: |
        sha256sum backup-${{ github.ref_name }}.tar.gz > backup-${{ github.ref_name }}.sha256
        scp backup-${{ github.ref_name }}.sha256 $REMOTE_USER@$REMOTE_SERVER:$REMOTE_PATH