name: Lint Terraform Code

on:
  push:
    branches:
      - andreas-pw.7.1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Lint Terraform Code
      run: |
        tflint --recursive > tflint_output.txt
        if [ $? -ne 0 ]; then
          echo "Linting failed"
          cat tflint_output.txt
          exit 1
        fi
        cat tflint_output.txt