name: PW.7.1

on:
  push:
    branches:
      - andreas-pw.7.1
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build
      run: echo "Building the project..."

  review:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Manual approval
      uses: hmarr/auto-approve-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.PAT }}

  publish:
    needs: review
    runs-on: ubuntu-latest

    steps:
    - name: Publish
      run: echo "Publishing the project..."