name: PW.7.1 

on:
  push:
    branches-ignore:
      - main  # Skip main branch pushes for this workflow
    paths:
      - '**.tf'  # Trigger only on changes to .tf files

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    name: Terraform Test and Validate
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
      # Step 2: Initialize Terraform (without backend)
      - name: Terraform Init
        id: terraform-init
        run: terraform init -backend=false
     

      # Step 3: Check Terraform formatting
      - name: Terraform Format Check
        id: terraform-fmt
        run: terraform fmt -check -recursive
        continue-on-error: true
        

      # Step 4: Validate Terraform configuration
      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate
      

      # Step 5: Run tfsec for security scanning
      - name: Terraform Security Scan (tfsec)
        id: terraform-tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true  
      # Step 6: Setup TFLint (for Terraform linting)
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest
        continue-on-error: true  
      # Step 7: Display TFLint version
      - name: TFLint Version
        run: tflint --version
        continue-on-error: true  
      # Step 8: Initialize TFLint plugins
      - name: TFLint Plugin Init
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Step 9: Run TFLint to check Terraform code quality
      - name: TFLint Run
        run: tflint
        continue-on-error: true