name: Manual Review of main and automatic review of other branches

on:
  push:
    branches:
      - pw.7.1
    
  jobs:
  manual_review:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

