name: PW.9.2

on: 
  push:
    branches:
      - andreas-pw.9.2

jobs:
  Setup-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Install OPA
        run: wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa && chmod +x opa && mv opa /usr/local/bin/

      - name: Run Terraform Init
        run: terraform init -backend=false
      - name: Terraform plan
          terraform plan -out=tfplan.binary

      - name: Write out Terraform plan
        run: cat tfplan.json
