name: Terraform OPA Security Scan

on: 
  push:
    branches:
      - andreas-pw.9.2

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OPA
        run: wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa && chmod +x opa && mv opa /usr/local/bin/

      - name: Run Terraform Plan
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - name: Write out Terraform plan
        run: cat tfplan.json
