name: RV.1.1

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  security-events: write
  contents: read

jobs:
  terrascan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4            

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.3
      - name: Run vulnerability scan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          install terrascan /usr/local/bin && rm terrascan
          terrascan scan -p ./iac-azure-terraform-example/

  vulnerabilities-in-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for vulnerabilities in dependencies
        uses: github/codeql-action/analyze@v2
        with:
          category: "dependency-scanning"

  ggshield-scan:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@v1.37.0
        env:
          GITGUARDIAN_TOKEN: ${{ secrets.GITGUARDIAN_TOKEN }}