name: Create and Upload Release with Git Archive

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create a compressed zip archive using git archive
      - name: Create release zip
        run: git archive --output=release.zip HEAD

      # Debug: Check if the zip file was created
      - name: Verify zip file creation
        run: |
          if [ ! -f release.zip ]; then
            echo "Error: release.zip was not created!"
            exit 1
          fi
          echo "release.zip exists."
          ls -lah release.zip

      # Generate SHA256 checksum
      - name: Generate SHA256 checksum
        run: sha256sum release.zip > release.zip.sha256

      # Verify checksum file
      - name: Verify checksum file
        run: |
          if [ ! -f release.zip.sha256 ]; then
            echo "Error: release.zip.sha256 was not created!"
            exit 1
          fi
          echo "release.zip.sha256 exists."
          cat release.zip.sha256

      # Upload release zip and checksum as artifacts
      - name: Upload release and checksum as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release.zip, release.zip.sha256
